name: Documentation Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      
permissions:
  contents: write
  pages: write
  id-token: write
  
jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Set up Node (optional, but caches npm)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # 3. Install dependencies (works even without package-lock.json)
      - name: Install dependencies
        run: npm install

      # 4. Build Docs – install docsify-cli + init
      - name: Build Docs
        run: |
          npm install -g docsify-cli
          docsify init ./docs --theme vue

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          allow_empty_commit: true
          force_orphan: true
          commit_message: "Deploy docs – ${{ github.sha }}"
