name: Generate Release Notes

on:
  release:
    types: [published]  # triggers when a release is published on GitHub
  workflow_dispatch: {}

jobs:
  release-notes:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Generate release notes from last 10 commits
      - name: Generate release notes
        id: notes
        uses: actions/github-script@v7
        with:
          script: |
            const { execSync } = require('child_process');
            // Get last 10 commits formatted as "- message (author)"
            const log = execSync('git log -10 --pretty=format:"- %s (%an)"').toString();
            core.setOutput("notes", `### Recent Changes\n${log}`);

      # Step 3: Create or update GitHub release with the notes
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.notes.outputs.notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
