name: Generate Release Notes

on:
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  generate-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        uses: cli/gh-actions@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate simple changelog (PR titles since last tag)
        run: |
          TAG=${{ github.event.release.tag_name || 'manual' }}
          echo "Generating release notes for $TAG"

          # Get last tag
          LAST_TAG=$(git describe --tags --abbrev=0 || echo "")
          if [ -n "$LAST_TAG" ]; then
            echo "Last tag: $LAST_TAG"
            PRS=$(gh pr list --search "merged:>=$LAST_TAG" --state merged --json title,number,author --limit 100) || true
          else
            PRS=$(gh pr list --state merged --json title,number,author --limit 100) || true
          fi

          echo "## Release notes for $TAG" > RELEASE_NOTES.md
          echo "" >> RELEASE_NOTES.md
          echo "$PRS" | jq -r '.[] | "- PR #\(.number): \(.title) (by \(.author.login))"' >> RELEASE_NOTES.md || true

      - name: Upload release notes artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: RELEASE_NOTES.md